### ISSUE TITLE
Experiment with Drag And Drop feature

### ISSUE THREAD

**Issue by ArturOle** [SoftwareEngineeringDreamTeam/DPG-PoC#2]
As there is no official implementation of drag and drop for files, we could try to spill some magic and force it to work.

**Comment by amrukwa** [comment]
are we leaning towards writing from scratch or using some other package to help ourselves out?

**Comment by ArturOle** [comment]
If there is something reasonable that could help then sure, we can use a package for this. Otherwise, we can try with implementation but for a later stage of the development (it is not the core feature)

**Comment by amrukwa** [comment]
what I have found as recommended by the authors of DearPyGui is the usage of filedialog from tkinter. However, the issue here is that the deployment presented in the examples is from DPG 0.6.268 - considerable changes till now - as well as usage of win32gui for the opening of the window for the file choosing - platform dependence on the code level introduced.
[https://github.com/RahulShagri/SimpleDrawing-Desktop-App](exemplary app)
[https://github.com/RahulShagri/SimpleDrawing-Desktop-App/blob/26ad0e2d13b6e25f05d162af31dfdc53bb3e5e07/tools/openTool.py#L13](callback in question)

**Comment by ArturOle** [comment]
We can try this approach. Create a branch and we could work on the PoC.
