### ISSUE TITLE
Fix data loading [dev branch]

### ISSUE THREAD

**Issue by ojaskula** [SoftwareEngineeringDreamTeam/DPG-PoC#82]
There is a chance that the CSV file data  won't load correctly. Ex. loading the file given in this issue, resulting in only one point loading.
[data.csv](https://github.com/SoftwareEngineeringDreamTeam/DPG-PoC/files/10315503/data.csv)

**Comment by Marsellus19** [comment]
Due to changes made in #78, the range of point values is 0 to 100 instead of 50 to 800. So there is nothing wrong. The attached file has values spanning up to 700. Therefore, only the first point is actually visible on the axis. When a file with correctly scaled values is loaded, everything is displayed properly. 

While we're here though, we might have to look and see if there's a safety mechanism preventing values > 100 (and < 0) from being loaded into memory. I have a feeling everything might be loaded as is. The points are not visible only because they do not fit inside the window. So to test it we would have to load a data point with a value of e.g. 101.
